Update K8sSecretUpdat

diff --git a/K8sSecretUpdat b/K8sSecretUpdat
--- a/K8sSecretUpdat
+++ b/K8sSecretUpdat
@@ -1,22 +1,51 @@
 #!/bin/bash
 
 DEFAULT_NAMESPACE="fraudsight-micro"
+SECRET_KEY="cassandra-endpoint"
+BACKUP_DIR="secret_backups"
 
 # Function to display command-line help
 display_help() {
-  echo "Usage: script.sh -s secret-name -i IP-to-remove [-n namespace]"
+  echo "Usage: script.sh -s secret-name -i IP-to-remove [-n namespace] [-r backup-name]"
   echo "Options:"
-  echo "  -s <secret-name>    Specify the name of the secret"
-  echo "  -i <IP-to-remove>   Specify the IP address to remove"
-  echo "  -n <namespace>      Specify the Kubernetes namespace (optional)"
-  echo "  -h                  Display this help message"
+  echo "  -s <secret-name>     Specify the name of the secret"
+  echo "  -i <IP-to-remove>    Specify the IP address to remove"
+  echo "  -n <namespace>       Specify the Kubernetes namespace (optional)"
+  echo "  -r <backup-name>     Roll back to the specified backup (optional)"
+  echo "  -h                   Display this help message"
 }
 
-while getopts ":s:i:n:h" opt; do
+# Function to create a backup of the secret
+backup_secret() {
+  local secret_name=$1
+  local namespace=$2
+  local backup_file="${BACKUP_DIR}/${secret_name}_$(date +'%Y%m%d%H%M%S').yaml"
+  kubectl get secret $secret_name -n $namespace -o yaml > $backup_file
+  echo "Created backup of secret: $backup_file"
+}
+
+# Function to roll back to the specified backup
+rollback_secret() {
+  local secret_name=$1
+  local namespace=$2
+  local backup_name=$3
+  local backup_file="${BACKUP_DIR}/${secret_name}_${backup_name}.yaml"
+  if kubectl apply -f $backup_file -n $namespace; then
+    echo "Rollback successful. Secret value has been reverted to the backup: $backup_file"
+  else
+    echo "Rollback failed. Unable to revert secret value."
+    exit 1
+  fi
+}
+
+# Parse command-line arguments
+while getopts ":s:i:n:r:h" opt; do
   case ${opt} in
     s) SECRET_NAME=$OPTARG;;
     i) IP_TO_REMOVE=$OPTARG;;
     n) NAMESPACE=$OPTARG;;
+    r) ROLLBACK=true
+       BACKUP_NAME=$OPTARG;;
     h) display_help
        exit 0;;
     \?) echo "Invalid option -$OPTARG" >&2
@@ -26,28 +55,57 @@ while getopts ":s:i:n:h" opt; do
   esac
 done
 
+# Check if rollback flag is set
+if [[ $ROLLBACK == true ]]; then
+  # Rollback to the specified backup
+  if [[ -z $SECRET_NAME ]]; then
+    echo "Secret name is required for rollback."
+    exit 1
+  fi
+  if [[ -z $BACKUP_NAME ]]; then
+    echo "Backup name is required for rollback."
+    exit 1
+  fi
+  if [[ -z $NAMESPACE ]]; then
+    NAMESPACE=$DEFAULT_NAMESPACE
+  fi
+  rollback_secret $SECRET_NAME $NAMESPACE $BACKUP_NAME
+  exit 0
+fi
+
 # Validate the input parameters
 if [[ -z $SECRET_NAME ]]; then
-  echo "Secret name is required. Usage: script.sh -s secret-name -i IP-to-remove [-n namespace]"
+  echo "Secret name is required. Usage: script.sh -s secret-name -i IP-to-remove [-n namespace] [-r backup-name]"
   exit 1
 fi
 
 if [[ -z $IP_TO_REMOVE ]]; then
-  echo "IP to remove is required. Usage: script.sh -s secret-name -i IP-to-remove [-n namespace]"
+  echo "IP to remove is required. Usage: script.sh -s secret-name -i IP-to-remove [-n namespace] [-r backup-name]"
   exit 1
 fi
 
 # Set the namespace to default if not provided
 NAMESPACE="${NAMESPACE:-$DEFAULT_NAMESPACE}"
 
+# Create the backup directory if it doesn't exist
+mkdir -p $BACKUP_DIR
+
+# Backup the current secret value before patching
+backup_secret $SECRET_NAME $NAMESPACE
+
 # Get the current value of the secret
-CURRENT_VALUE=$(kubectl get secret $SECRET_NAME -n $NAMESPACE -o jsonpath='{.data.cassandra-endpoint}' | base64 -d)
+CURRENT_VALUE=$(kubectl get secret $SECRET_NAME -n $NAMESPACE -o jsonpath="{.data['$SECRET_KEY']}" | base64 -d)
 
 # Remove the specified IP from the value
-UPDATED_VALUE=$(echo $CURRENT_VALUE | sed "s/$IP_TO_REMOVE//g" | sed 's/,,/,/g' | sed 's/,$//')
+UPDATED_VALUE=$(echo $CURRENT_VALUE | sed "s/\<$IP_TO_REMOVE\>//g" | sed 's/,,/,/g' | sed 's/^,//; s/,$//; s/,$/,/; s/,,/,/')
 
 # Update the secret with the new value
-kubectl patch secret $SECRET_NAME -n $NAMESPACE -p '{"data":{"cassandra-endpoint":"'$(echo -n $UPDATED_VALUE | base64)'"}}'
+if kubectl patch secret $SECRET_NAME -n $NAMESPACE -p $'{"data":{"'$SECRET_KEY'":"'$(echo -n $UPDATED_VALUE | base64)'"}}'; then
+  echo "Kubectl patch successful."
+else
+  echo "Kubectl patch failed."
+  exit 1
+fi
 
 # Display the updated and old values
 echo "Updated values:"
@@ -55,10 +113,3 @@ echo $UPDATED_VALUE
 echo ""
 echo "Old values:"
 echo $CURRENT_VALUE
-
-#UPDATED_VALUE=$(echo $CURRENT_VALUE | sed "s/\<$IP_TO_REMOVE\>//g" | sed 's/,,/,/g' | sed 's/^,//; s/,$//; s/,$/,/; s/,,/,/')
-
-
-
-
-
