Update K8sSecretUpdat

diff --git a/K8sSecretUpdat b/K8sSecretUpdat
--- a/K8sSecretUpdat
+++ b/K8sSecretUpdat
@@ -19,7 +19,16 @@ display_help() {
 backup_secret() {
   local secret_name=$1
   local namespace=$2
-  local backup_file="${BACKUP_DIR}/${secret_name}_$(date +'%Y%m%d%H%M%S').yaml"
+  local backup_file=""
+
+  # Check if original backup already exists
+  if [[ -f "${BACKUP_DIR}/${secret_name}-original.yaml" ]]; then
+    local backup_count=$(find $BACKUP_DIR -name "${secret_name}-backup-*" | wc -l)
+    backup_file="${BACKUP_DIR}/${secret_name}-backup-$(($backup_count + 1)).yaml"
+  else
+    backup_file="${BACKUP_DIR}/${secret_name}-original.yaml"
+  fi
+
   kubectl get secret $secret_name -n $namespace -o yaml > $backup_file
   echo "Created backup of secret: $backup_file"
 }
@@ -29,7 +38,22 @@ rollback_secret() {
   local secret_name=$1
   local namespace=$2
   local backup_name=$3
-  local backup_file="${BACKUP_DIR}/${secret_name}_${backup_name}.yaml"
+  local backup_file=""
+
+  if [[ $backup_name == "original" ]]; then
+    backup_file="${BACKUP_DIR}/${secret_name}-original.yaml"
+  elif [[ $backup_name == "last" ]]; then
+    local latest_backup=$(find $BACKUP_DIR -name "${secret_name}-backup-*" | sort -r | head -n 1)
+    backup_file="$latest_backup"
+  else
+    backup_file="${BACKUP_DIR}/${secret_name}-backup-$backup_name.yaml"
+  fi
+
+  if [[ ! -f "$backup_file" ]]; then
+    echo "Backup not found: $backup_file"
+    exit 1
+  fi
+
   if kubectl apply -f $backup_file -n $namespace; then
     echo "Rollback successful. Secret value has been reverted to the backup: $backup_file"
   else
@@ -109,7 +133,4 @@ fi
 
 # Display the updated and old values
 echo "Updated values:"
-echo $UPDATED_VALUE
-echo ""
-echo "Old values:"
-echo $CURRENT_VALUE
+echo $
